name: Build Resume
on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Google Fonts
        run: |
          wget -O Inter.zip https://fonts.google.com/download?family=Inter
          unzip -d inter/ Inter.zip
          mv -v inter/static /usr/share/fonts/Inter
          ls -l /usr/share/fonts/Inter
          fc-cache -fv
        
      - uses: yusancky/setup-typst@v2
        id: setup-typst
        with:
            version: 'v0.9.0'

      - name: Get current date
        id: date
        run: echo "DATE=$(date +%Y-%m-%d-%H-%M)" >> $GITHUB_ENV

      - run: typst compile resume.typ "jim-b-resume-${{ env.DATE }}".pdf

      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: "jim-b-resume-${{ env.DATE }}"
          path: "*.pdf"
